name: mediscantstv2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  camera: ^0.10.6
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  # tflite: ^1.1.2
  # tflite_flutter: ^0.10.4
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
  - assets/
  uses-material-design: true
